### ISSUE TITLE
crypt salt can't be auto assigned from "password_field"

### ISSUE THREAD

**Issue by rcmorano** [copiousfreetime/htauth#12]
Ohai,

I've been trying to use this [chef cookbook](https://github.com/redguide/htpasswd) for creating 'htpasswd' files and came across with a problem that is related to the way the 'htauth' gem [auto assigns a 'crypt' salt](https://github.com/copiousfreetime/htauth/blob/master/lib/htauth/algorithm.rb#L44).

It seems that it takes a 2-bytes string from the password (if I'm not assuming it wrong), but in the case that the 2 characteres taken are, for example, '$2' as it was in my case, it violates the [supported salts](http://ruby-doc.org/core-2.2.3/String.html#method-i-crypt) and rises an exception:

```
irb(main):001:0> pazz = "testing"
=> "testing"
irb(main):002:0> pazz.crypt('$2')
Errno::EINVAL: Invalid argument - crypt
    from (irb):2:in `crypt'
    from (irb):2
    from /opt/chef/embedded/bin/irb:11:in `<main>'
irb(main):003:0> 
```

I've replaced the method for getting the 2-bytes alphanumeric string for [this simple shuffle of characters](http://stackoverflow.com/questions/88311/how-best-to-generate-a-random-string-in-ruby#comment21462228_88341) and it worked fine!

Bests!

**Comment by copiousfreetime** [comment]
@rcmorano I'm not exactly sure what you are attempting to do there. The method you are referencing ([algorithms_from_field](https://github.com/copiousfreetime/htauth/blob/master/lib/htauth/algorithm.rb#L34)) in htauth isn't about creating a salt, its is for guessing the type of password encoding in the file from the password string, and then retrieving the appropriate salt based on the guessed algorithm. The line you are pointing to is extracting the salt from a password field in a `crypt()` password entry.

The generation of a new `crypt()` password entry is done in [crypt.rb](https://github.com/copiousfreetime/htauth/blob/master/lib/htauth/crypt.rb) and its picks random salt chars from [this list](https://github.com/copiousfreetime/htauth/blob/master/lib/htauth/algorithm.rb#L10). That list is the same as the list mentioned in [`String#crypt`](http://ruby-doc.org/core-2.2.3/String.html#method-i-crypt). 

As for using `#shuffle` well, htauth was authored before `Array#shuffle` was added to the ruby std library :smile:.

Can you provide a broader context to the problem you are working on so that we can best figure out how I can assist?

**Comment by derhecht** [comment]
btw problem still exists... I'm not sure but it seems when calling
htauth-2.0.0/lib/htauth/passwd_entry.rb:106:in `authenticated?' with password
it will result in this error
seems crypt is uninitialized so @salt is empty?

**Comment by copiousfreetime** [comment]
@derhecht do you have an example test? Its been a while since this ticket had any activity, and well - i probably have some spare time to work on this :-)

**Comment by derhecht** [comment]
use 
chef with
htpasswd cookbook

or have a look at:
def user_entry
  HTAuth::PasswdFile.new(new_resource.file).fetch(new_resource.user)
rescue
  nil
end

def user_set?
  user_entry.authenticated?(new_resource.password) unless user_entry.nil?
end

this is the call made to user_entry.authenticated which causes the error

**Comment by derhecht** [comment]
may Chef 12 (which I currently use) is shipped with a ruby not supporting string.crypt with parameter?

**Comment by derhecht** [comment]
looks like thats it
https://ruby-doc.org/core-1.9.3/String.html#method-i-crypt vs
https://ruby-doc.org/core-2.7.0/String.html#method-i-crypt

**Comment by derhecht** [comment]
ok, the salt is (quite often) e.g.: "$2" -> password.crypt("$2") will result in an error
password.crypt("aA") is ok, as documented
salt generation seems to be invalid

**Comment by derhecht** [comment]
sooo, how can inject the salt param into the crypt initialize?

**Comment by derhecht** [comment]
ok, got it. will call e.g. HTAuth::Crypt.new(:salt => 'aA') in chef cookbook before calling e.g. authenticated -> problem "solved"
salt generation seems invalid at all as e.g. "$" character is inside

**Comment by copiousfreetime** [comment]
cool - good to know - The $ in a password entry generally is part of determining type of algorithm used for the password. And yes the `$` character is invalid as a salt in the `crypt(3)` algorithm.

**Comment by derhecht** [comment]
you closed and working on a patch? i mean the generation is never the less wrong and should be fixed here or not?

**Comment by copiousfreetime** [comment]
@derhecht My apologies, I thought you were saying your problem was solved.  

I've just taken a look at things, I think I may see the problem. Are you seeing lines like this in your password file? 

```
user:$2y$05$bGe6k3iJLIPOKHmyE2eOOeu8VcTzOjC3dmsCU2X3gTGUyL6cz2vUi
```

That means that this password is bcrypt encrypted, not `crypt(3)` encrypted. And at the moment it looks like htauth doesn't support bcrypt encryption in the htpasswd file, that's because I don't think bcrypt was part of the apache `htpasswd/htdigest` setup when I wrote htauth originally (which was quite a while ago).

I'll implement bcrypt algorithm handling and do a new release in the next couple of days.

What program are you using to generate the password file originally?

**Comment by derhecht** [comment]
unsure. yes I have password files like you mentioned.
but my investigation just come to the fact that it will call your password.crypt function in your crypt class with a salt like "$2" which was generated by gen_salt which is illegal for password.crypt call.
so I don't get in which way this does belong to bcrypt. but it is your code and I not dived into it completely so may go on and we will see.
as mentioned I just call/check with: HTAuth::PasswdFile.new('/path/to/file).fetch('username').authenticated('password')

**Comment by derhecht** [comment]
in the end I don't get why your salt generation is so complex. I work around with:

```
def generate_code(number)
  charset = Array('A'..'Z') + Array('a'..'z') + Array('0'..'9') + Array('.') + Array('/')
  Array.new(number) { charset.sample }.join
end
```

and get salt by: `generate_code(2)`

**Comment by copiousfreetime** [comment]
> as mentioned I just call/check with: HTAuth::PasswdFile.new('/path/to/file).fetch('username').authenticated('password')

I have a feeling that this `/path/to/file` already exists and is created through some other mechanism, that is not htuath gem. 

The `$2` is being pulled from the existing record in the file. When the first 2 bytes of the password field is a `$2` that means that it is a bcrypt password, and currently htauth doesn't handle that situation, so it is defaulting to the crypt passwd altorigthm, and is attempting to use `$2` from the file as the salt for the crypt passwd algorithm. This is a bug. I'll be fixing this.

As for why the `gen_salt` method in htauth is complex. htauth was originally written before `Array#sample` existed in the ruby core library. It basically does what `Array#sample` does, and it also is used by both the MD5 algorithm and the crypt algorithm which is why it uses 8 chars by default instead of 2.

There will be a new release of htauth in the coming days that updates it for algorithms supported, and also some upcates to the code style to bring it inline with more modern ruby.

**Comment by copiousfreetime** [comment]
@rcmorano @derhecht Version 2.1 pushed up to rubygems that should resolve this issue. Please check it out and make sure it resolves these issues.

**Comment by rcmorano** [comment]
Thank you very much @copiousfreetime!

**Comment by copiousfreetime** [comment]
@rcmorano and I must apologize for not realizing that the `$2` issue you reported so long ago was actually just bcrypt entries. I feel really bad about that.
